<?php
/**
 * AppStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fleximize Applications API
 *
 * Welcome to the Fleximize API!    Please be aware this version of the API is currently in beta.   If you encouter any problems or have any questions and inquiries, please contact the development team. Thank you.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: development@fleximize.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * AppStatus Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AppStatus
{
    /**
     * Possible values of this enum
     */
    const APPROVED = 'Approved';
const APPROVED__OFFER_EXPIRED = 'Approved (Offer Expired)';
const CANCELLED = 'Cancelled';
const DEPOSITED = 'Deposited';
const FAILED = 'Failed';
const UNDER_REVIEW = 'Under Review';
const TEST = 'Test';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::APPROVED,
self::APPROVED__OFFER_EXPIRED,
self::CANCELLED,
self::DEPOSITED,
self::FAILED,
self::UNDER_REVIEW,
self::TEST,        ];
    }
}
