<?php
/**
 * ApplicationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fleximize Applications API
 *
 * Welcome to the Fleximize API!    If you encouter any problems or have any questions and inquiries, please contact the development team. Thank you.  **Important Notice:**  By submitting application, you confirm that you have obtained the consent of all individuals associated with it (directors, personal guarantors, mortgagors and shareholders etc). The personal information we have collected from you will be shared with fraud prevention agencies. This is to prevent fraud and money laundering and to verify the identity of all individuals supplied and associated with this application. If fraud is detected, you and these individuals could be refused certain services, finance and employment. Further details on the processing of information and the individual’s data processing rights can be found [here](https://www.cifas.org.uk/fpn).
 *
 * OpenAPI spec version: 2.0.0
 * Contact: development@fleximize.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ApplicationTest Class Doc Comment
 *
 * @category    Class
 * @description Application object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApplicationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Application"
     */
    public function testApplication()
    {
    }

    /**
     * Test attribute "is_test"
     */
    public function testPropertyIsTest()
    {
    }

    /**
     * Test attribute "business_type_id"
     */
    public function testPropertyBusinessTypeId()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "registration_number"
     */
    public function testPropertyRegistrationNumber()
    {
    }

    /**
     * Test attribute "title_id"
     */
    public function testPropertyTitleId()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "loan_amount"
     */
    public function testPropertyLoanAmount()
    {
    }

    /**
     * Test attribute "term"
     */
    public function testPropertyTerm()
    {
    }

    /**
     * Test attribute "funding_urgency"
     */
    public function testPropertyFundingUrgency()
    {
    }

    /**
     * Test attribute "loan_purpose_id"
     */
    public function testPropertyLoanPurposeId()
    {
    }

    /**
     * Test attribute "other_purpose"
     */
    public function testPropertyOtherPurpose()
    {
    }

    /**
     * Test attribute "internal_id"
     */
    public function testPropertyInternalId()
    {
    }

    /**
     * Test attribute "account_score_customer"
     */
    public function testPropertyAccountScoreCustomer()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "privacy_policy_consent"
     */
    public function testPropertyPrivacyPolicyConsent()
    {
    }

    /**
     * Test attribute "cra_checks_consent"
     */
    public function testPropertyCraChecksConsent()
    {
    }

    /**
     * Test attribute "refer_consent"
     */
    public function testPropertyReferConsent()
    {
    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {
    }
}
