<?php
/**
 * CompanyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fleximize Applications API
 *
 * Welcome to the Fleximize API!    If you encouter any problems or have any questions and inquiries, please contact the development team. Thank you.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: development@fleximize.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CompanyTest Class Doc Comment
 *
 * @category    Class
 * @description Object holding company data
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompanyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Company"
     */
    public function testCompany()
    {
    }

    /**
     * Test attribute "vat_no"
     */
    public function testPropertyVatNo()
    {
    }

    /**
     * Test attribute "monthly_sales"
     */
    public function testPropertyMonthlySales()
    {
    }

    /**
     * Test attribute "date_of_creation"
     */
    public function testPropertyDateOfCreation()
    {
    }

    /**
     * Test attribute "trading_date"
     */
    public function testPropertyTradingDate()
    {
    }

    /**
     * Test attribute "same_address"
     */
    public function testPropertySameAddress()
    {
    }

    /**
     * Test attribute "registered_address"
     */
    public function testPropertyRegisteredAddress()
    {
    }

    /**
     * Test attribute "trading_address"
     */
    public function testPropertyTradingAddress()
    {
    }

    /**
     * Test attribute "directors"
     */
    public function testPropertyDirectors()
    {
    }

    /**
     * Test attribute "shareholders"
     */
    public function testPropertyShareholders()
    {
    }
}
